"""Freeze the data contract: hashes and versions of every input the pipeline reads.

The lock file lives under config/ because .gitignore excludes data/*, so a record
written next to the data would vanish on a fresh clone. Raw and staging data are
only ever read.

Modes:
  (no flag)          scan every contract input and write config/data-contract.lock.json
  --check            recompute and compare against the lock file, non-zero on drift
                     (--only ROLE and --skip-pbf narrow it to part of the contract)
  --extract-fixture  cut the frozen regression bicycles out of the full staging CSV
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import platform
import sys
import tempfile
from importlib import metadata
from pathlib import Path
from typing import Any
from zipfile import BadZipFile, ZipFile

import osmium.io
from pyproj import Transformer
from shapely.geometry import shape
from shapely.ops import transform as shapely_transform

PROJECT_ROOT = Path(__file__).resolve().parents[1]

CONTRACT_VERSION = "1.0"
GENERATED_BY = "scripts/freeze_data_contract.py"
NOTE = (
    "Generated by scripts/freeze_data_contract.py — do not edit by hand. "
    "Run the script to regenerate, and `--check` to verify."
)

BOUNDARY_PATH = "config/xiamen-island.geojson"
BOUNDARY_GENERATED_BY = "scripts/extract_xiamen_island_boundary.py"
SAMPLE_PATH = "config/regression-sample.json"
LOCK_PATH = "config/data-contract.lock.json"
MANIFEST_PATH = "data/staging/conversion-manifest.json"
RAW_DIR = "data/raw"
STAGING_DIR = "data/staging"
FIXTURE_DIR = "tests/fixtures"
FIXTURE_PATH = "tests/fixtures/regression-sample-20201221.csv"
UV_LOCK_PATH = "uv.lock"

ROLES: tuple[str, ...] = ("boundary", "config", "fixture", "osm_pbf", "raw", "staging")
IGNORED_NAMES = {".DS_Store", ".gitkeep"}
# ADR-0011 retired the electronic-fence data: no analysis, no database, no frontend.
# The files stay on disk as received, and the notebook prototypes the ADR keeps as
# research evidence still read them, but no pipeline stage does. Discovery skips them
# rather than lock bytes that nothing downstream of this contract consumes.
RETIRED_DIRS: tuple[str, ...] = (
    "data/raw/electronic-fence",
    "data/staging/electronic-fence",
)
TOOLING_PACKAGES = ("pandas", "numpy", "pyproj", "shapely", "osmium", "pyspark")
UTM_CRS = "EPSG:32650"
# mkstemp creates 0600; both products of this script are committed files.
COMMITTED_FILE_MODE = 0o644


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def is_excel_workbook(path: Path) -> bool:
    try:
        with ZipFile(path) as archive:
            names = set(archive.namelist())
    except (BadZipFile, OSError):
        return False
    return "xl/workbook.xml" in names and "[Content_Types].xml" in names


def read_csv_shape(path: Path) -> dict[str, Any] | None:
    """Header, column count and data row count, or None when this is not a text CSV.

    A table whose first column is named TIME also gets the period it covers, so a
    claim like "the weather table is hourly over 12-20..12-25" has a source.
    """
    if is_excel_workbook(path):
        return None
    try:
        with path.open(encoding="utf-8", newline="") as stream:
            reader = csv.reader(stream)
            try:
                header = next(reader)
            except StopIteration:
                return None
            data_rows = 0
            first = last = None
            for row in reader:
                data_rows += 1
                last = row[0] if row else None
                if first is None:
                    first = last
    except UnicodeDecodeError:
        return None
    shape_fields: dict[str, Any] = {
        "data_rows": data_rows,
        "columns": len(header),
        "header": header,
    }
    if header and header[0].strip().upper() == "TIME" and data_rows:
        shape_fields["time_range"] = {"first": first, "last": last}
    return shape_fields


def discover(root: Path) -> list[tuple[str, str]]:
    """Every contract input as (path relative to root, role), sorted by path."""
    found: list[tuple[str, str]] = []

    def add(path: Path, role: str) -> None:
        if not path.is_file() or path.name in IGNORED_NAMES or path.name.startswith("."):
            return
        relative = path.relative_to(root).as_posix()
        if any(relative.startswith(f"{directory}/") for directory in RETIRED_DIRS):
            return
        found.append((relative, role))

    add(root / BOUNDARY_PATH, "boundary")
    add(root / SAMPLE_PATH, "config")

    for path in sorted((root / RAW_DIR).rglob("*")):
        add(path, "osm_pbf" if path.name.endswith(".osm.pbf") else "raw")

    for path in sorted((root / STAGING_DIR).rglob("*")):
        if path.suffix == ".csv":
            add(path, "staging")
        elif path.suffix == ".json":
            add(path, "config")

    for path in sorted((root / FIXTURE_DIR).iterdir()) if (root / FIXTURE_DIR).is_dir() else []:
        if path.suffix in {".csv", ".parquet"}:
            add(path, "fixture")

    return sorted(found)


def read_manifest(root: Path) -> dict[str, dict[str, Any]]:
    """conversion-manifest.json indexed by path, for both sides of each conversion.

    The manifest is the conversion script's own product; this script absorbs its
    conclusions rather than replacing it.
    """
    path = root / MANIFEST_PATH
    if not path.is_file():
        return {}
    index: dict[str, dict[str, Any]] = {}
    for record in json.loads(path.read_text(encoding="utf-8")).get("files", []):
        for side in ("source", "destination"):
            index[record[side]] = {
                "field": f"{side}_sha256",
                "sha256": record.get(f"{side}_sha256"),
                "data_rows": record.get("data_rows"),
            }
    return index


def manifest_disagreements(root: Path, lock: dict[str, Any]) -> list[str]:
    """Where conversion-manifest.json and the freshly computed hashes differ."""
    index = read_manifest(root)
    problems = []
    for entry in lock["entries"]:
        record = index.get(entry["path"])
        if record is None or not record["sha256"]:
            continue
        if record["sha256"] != entry["sha256"]:
            problems.append(
                f"MANIFEST    {entry['path']} disagrees with {MANIFEST_PATH}\n"
                f"  manifest {record['field']} {record['sha256']}\n"
                f"  actual   sha256 {entry['sha256']}\n"
                f"  the recomputed value is authoritative and is what the lock file records"
            )
    return problems


def read_pbf_header(path: Path) -> dict[str, Any]:
    reader = osmium.io.Reader(str(path))
    try:
        header = reader.header()
        keys = (
            "generator",
            "osmosis_replication_timestamp",
            "osmosis_replication_sequence_number",
            "osmosis_replication_base_url",
            "sorting",
        )
        fields: dict[str, Any] = {key: (header.get(key) or None) for key in keys}
        box = header.box()
        fields["bbox"] = (
            {
                "min_lon": round(box.bottom_left.lon, 7),
                "min_lat": round(box.bottom_left.lat, 7),
                "max_lon": round(box.top_right.lon, 7),
                "max_lat": round(box.top_right.lat, 7),
            }
            if box.valid()
            else None
        )
        return fields
    finally:
        reader.close()


def read_boundary(path: Path) -> dict[str, Any]:
    feature = json.loads(path.read_text(encoding="utf-8"))
    properties = feature.get("properties", {})
    geometry = shape(feature["geometry"])
    to_utm = Transformer.from_crs("EPSG:4326", UTM_CRS, always_xy=True).transform
    return {
        "osm_type": properties.get("osm_type"),
        "osm_id": properties.get("osm_id"),
        "osm_version": properties.get("osm_version"),
        "geometry_type": feature["geometry"]["type"],
        "polygon_parts": len(getattr(geometry, "geoms", [geometry])),
        "area_km2_utm": round(shapely_transform(to_utm, geometry).area / 1e6, 3),
        "generated_by": BOUNDARY_GENERATED_BY,
    }


def build_entry(
    root: Path,
    relative_path: str,
    role: str,
    pbf_sha256: str | None,
    manifest: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    path = root / relative_path
    entry: dict[str, Any] = {
        "path": relative_path,
        "role": role,
        "bytes": path.stat().st_size,
        "sha256": sha256(path),
    }
    if role in {"raw", "staging", "fixture"} and path.suffix == ".csv":
        shape_fields = read_csv_shape(path)
        if shape_fields is not None:
            entry.update(shape_fields)
    if role == "fixture" and path.suffix == ".parquet":
        try:
            import pyarrow.parquet as pq

            table = pq.read_table(path)
            entry["data_rows"] = table.num_rows
            entry["columns"] = table.column_names
        except (OSError, ImportError):
            pass
    if role == "osm_pbf":
        entry.update(read_pbf_header(path))
    if role == "boundary":
        entry.update(read_boundary(path))
        entry["source_pbf_sha256"] = pbf_sha256
    if "data_rows" not in entry:
        # Excel workbooks cannot be counted cheaply; the conversion manifest already did.
        record = manifest.get(relative_path)
        if record is not None and record["data_rows"] is not None:
            entry["data_rows"] = record["data_rows"]
    return entry


def collect_tooling(root: Path) -> dict[str, Any]:
    tooling: dict[str, Any] = {"python": platform.python_version()}
    for package in TOOLING_PACKAGES:
        try:
            tooling[package] = metadata.version(package)
        except metadata.PackageNotFoundError:
            tooling[package] = None
    uv_lock = root / UV_LOCK_PATH
    tooling["uv_lock_sha256"] = sha256(uv_lock) if uv_lock.is_file() else None
    return tooling


def build_lock(
    root: Path, roles: set[str], pbf_sha256: str | None = None
) -> dict[str, Any]:
    discovered = [(path, role) for path, role in discover(root) if role in roles]
    if pbf_sha256 is None:
        pbf_sha256 = next(
            (sha256(root / path) for path, role in discovered if role == "osm_pbf"), None
        )
    manifest = read_manifest(root)
    entries = [
        build_entry(root, path, role, pbf_sha256, manifest) for path, role in discovered
    ]
    return {
        "contract_version": CONTRACT_VERSION,
        "generated_by": GENERATED_BY,
        "note": NOTE,
        "tooling": collect_tooling(root),
        "entries": entries,
    }


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
        os.chmod(temporary_name, COMMITTED_FILE_MODE)
        os.replace(temporary_name, path)
    except BaseException:
        Path(temporary_name).unlink(missing_ok=True)
        raise


def load_sample(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def sample_bicycle_ids(sample: dict[str, Any]) -> list[str]:
    return [entry["bicycle_id"] for entry in sample["bicycles"]]


def count_points_per_bicycle(path: Path, wanted: set[str]) -> dict[str, int]:
    """Points per BICYCLE_ID, filling the id forward as the staging layout requires."""
    counts = dict.fromkeys(wanted, 0)
    with path.open(encoding="utf-8", newline="") as stream:
        reader = csv.reader(stream)
        header = next(reader)
        id_column = header.index("BICYCLE_ID")
        current = ""
        for row in reader:
            current = row[id_column] or current
            if current in counts:
                counts[current] += 1
    return counts


def sample_problems(sample: dict[str, Any], source: Path, root: Path) -> list[str]:
    """Every way the frozen manifest can disagree with the file it was cut from."""
    wanted = sample_bicycle_ids(sample)
    counts = count_points_per_bicycle(source, set(wanted))
    problems: list[str] = []
    for entry in sample["bicycles"]:
        bicycle_id = entry["bicycle_id"]
        found = counts[bicycle_id]
        if found == 0:
            problems.append(
                f"SAMPLE      {bicycle_id} is listed in the frozen sample "
                f"but has no points in {relative_to(source, root)}"
            )
        elif found != entry["points"]:
            problems.append(
                f"SAMPLE      {bicycle_id} point count disagrees with "
                f"{relative_to(source, root)}\n"
                f"  expected points {entry['points']}\n"
                f"  actual   points {found}"
            )
    total = sum(counts.values())
    expected_total = sample["totals"]["points"]
    if not problems and total != expected_total:
        problems.append(
            f"SAMPLE      total point count disagrees with {relative_to(source, root)}\n"
            f"  expected points {expected_total}\n"
            f"  actual   points {total}"
        )
    return problems


def relative_to(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root).as_posix()
    except ValueError:
        return path.name


class _Absent:
    def __repr__(self) -> str:
        return "<absent>"


ABSENT = _Absent()


def field_differences(
    recorded: dict[str, Any], actual: dict[str, Any]
) -> list[tuple[str, Any, Any]]:
    """Fields that disagree, hashes and sizes first, then the role-specific ones."""
    leading = [key for key in ("sha256", "bytes") if key in recorded or key in actual]
    trailing = sorted((set(recorded) | set(actual)) - {"path", "role", *leading})
    return [
        (key, recorded.get(key, ABSENT), actual.get(key, ABSENT))
        for key in leading + trailing
        if recorded.get(key, ABSENT) != actual.get(key, ABSENT)
    ]


def report_differences(
    recorded_entries: dict[str, dict[str, Any]],
    actual_entries: dict[str, dict[str, Any]],
) -> list[str]:
    problems: list[str] = []
    for path, recorded in recorded_entries.items():
        actual = actual_entries.get(path)
        if actual is None:
            problems.append(
                f"MISSING     {path}\n"
                f"  recorded sha256 {recorded['sha256']}\n"
                f"  the file does not exist on disk"
            )
            continue
        differences = field_differences(recorded, actual)
        if differences:
            lines = "\n".join(
                f"  expected {key} {expected!r}\n  actual   {key} {found!r}"
                for key, expected, found in differences
            )
            problems.append(f"CHANGED     {path}\n{lines}")
    for path in actual_entries.keys() - recorded_entries.keys():
        problems.append(
            f"UNRECORDED  {path}\n  present on disk but absent from the lock file"
        )
    return problems


def selected_roles(args: argparse.Namespace) -> set[str]:
    roles = set(args.only) if args.only else set(ROLES)
    if args.skip_pbf:
        roles.discard("osm_pbf")
    return roles


def check_regression_sample(args: argparse.Namespace, roles: set[str]) -> list[str]:
    """The frozen bicycle manifest against the staging file and the committed fixture."""
    if not args.sample.is_file():
        return [f"SAMPLE      the frozen sample is missing: {args.sample}"]

    sample = load_sample(args.sample)
    problems: list[str] = []
    sources = []
    if "staging" in roles:
        sources.append(args.project_root / sample["source_file"])
    if "fixture" in roles:
        sources.append(args.fixture)
    for source in sources:
        if source.is_file():
            problems += sample_problems(sample, source, args.project_root)
        else:
            print(
                f"note: sample check skipped, {source} is not present",
                file=sys.stderr,
            )
    return problems


def run_check(args: argparse.Namespace) -> int:
    if not args.lock.is_file():
        print(
            f"lock file not found: {args.lock}\n"
            f"run {GENERATED_BY} without --check to create it",
            file=sys.stderr,
        )
        return 1

    recorded_lock = json.loads(args.lock.read_text(encoding="utf-8"))
    roles = selected_roles(args)
    recorded_entries = {
        entry["path"]: entry
        for entry in recorded_lock["entries"]
        if entry["role"] in roles
    }

    pbf_sha256 = None
    if "osm_pbf" not in roles:
        pbf_sha256 = next(
            (
                entry.get("source_pbf_sha256")
                for entry in recorded_entries.values()
                if entry["role"] == "boundary"
            ),
            None,
        )
    actual_lock = build_lock(args.project_root, roles, pbf_sha256)
    actual_entries = {entry["path"]: entry for entry in actual_lock["entries"]}

    problems = report_differences(recorded_entries, actual_entries)
    problems += manifest_disagreements(args.project_root, actual_lock)
    problems += check_regression_sample(args, roles)
    for problem in problems:
        print(problem, file=sys.stderr)

    for key, recorded_value in recorded_lock.get("tooling", {}).items():
        actual_value = actual_lock["tooling"].get(key)
        if recorded_value != actual_value:
            print(
                f"note: tooling {key} was {recorded_value}, now {actual_value} "
                f"(informational, not a contract violation)"
            )

    if problems:
        print(
            f"data contract check FAILED: {len(problems)} problem(s) "
            f"across {len(recorded_entries)} recorded entries",
            file=sys.stderr,
        )
        return 1
    print(f"data contract check passed: {len(recorded_entries)} entries verified")
    return 0


def run_extract_fixture(args: argparse.Namespace) -> int:
    sample = load_sample(args.sample)
    source = args.project_root / sample["source_file"]
    if not source.is_file():
        print(f"source file not found: {source}", file=sys.stderr)
        return 1

    problems = sample_problems(sample, source, args.project_root)
    if problems:
        for problem in problems:
            print(problem, file=sys.stderr)
        print("fixture not written", file=sys.stderr)
        return 1

    wanted = set(sample_bicycle_ids(sample))
    with source.open(encoding="utf-8", newline="") as stream:
        reader = csv.reader(stream)
        header = next(reader)
        id_column = header.index("BICYCLE_ID")
        current = ""
        kept = []
        for row in reader:
            current = row[id_column] or current
            if current in wanted:
                kept.append(row)
    kept.sort(key=lambda row: int(row[0]))

    destination = args.fixture
    destination.parent.mkdir(parents=True, exist_ok=True)
    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", suffix=".tmp", dir=destination.parent
    )
    try:
        with os.fdopen(
            file_descriptor, "w", encoding="utf-8", newline=""
        ) as output:
            writer = csv.writer(output, lineterminator="\n")
            writer.writerow(header)
            writer.writerows(kept)
        os.chmod(temporary_name, COMMITTED_FILE_MODE)
        os.replace(temporary_name, destination)
    except BaseException:
        Path(temporary_name).unlink(missing_ok=True)
        raise

    round_trip = sample_problems(sample, destination, args.project_root)
    if round_trip:
        for problem in round_trip:
            print(problem, file=sys.stderr)
        print(
            f"{relative_to(destination, args.project_root)} does not re-read as the "
            f"frozen sample; the source file may not group each BICYCLE_ID contiguously",
            file=sys.stderr,
        )
        return 1

    print(
        f"wrote {destination} ({len(kept)} rows, "
        f"{len(wanted)} bicycles from {relative_to(source, args.project_root)})"
    )
    print(f"run {GENERATED_BY} without flags to record the new fixture hash")
    return 0


def run_write(args: argparse.Namespace) -> int:
    lock = build_lock(args.project_root, selected_roles(args))
    write_json(args.lock, lock)
    print(f"wrote {args.lock} ({len(lock['entries'])} entries)")

    problems = manifest_disagreements(args.project_root, lock)
    for problem in problems:
        print(problem, file=sys.stderr)
    return 1 if problems else 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=PROJECT_ROOT)
    parser.add_argument("--lock", type=Path, default=None)
    parser.add_argument("--sample", type=Path, default=None)
    parser.add_argument("--fixture", type=Path, default=None)
    parser.add_argument(
        "--only",
        action="append",
        choices=ROLES,
        default=None,
        help="restrict --check to these roles (repeatable)",
    )
    parser.add_argument(
        "--skip-pbf",
        action="store_true",
        help="exclude the OSM PBF from --check, for environments without the 41 MB file",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--extract-fixture", action="store_true")
    args = parser.parse_args(argv)
    if (args.only or args.skip_pbf) and not args.check:
        # A partial scan would silently replace the committed lock with a partial
        # record; narrowing the scope only ever makes sense when verifying.
        parser.error("--only and --skip-pbf apply to --check only")
    args.project_root = args.project_root.resolve()
    if args.lock is None:
        args.lock = args.project_root / LOCK_PATH
    if args.sample is None:
        args.sample = args.project_root / SAMPLE_PATH
    if args.fixture is None:
        sample = load_sample(args.sample) if args.sample.is_file() else {}
        args.fixture = args.project_root / sample.get("fixture_file", FIXTURE_PATH)
    return args


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if args.check:
        return run_check(args)
    if args.extract_fixture:
        return run_extract_fixture(args)
    return run_write(args)


if __name__ == "__main__":
    raise SystemExit(main())
